### ISSUE TITLE
Error running chaincode: Failed to generate platform-specific docker build: Failed to pull hyperledger/fabric-ccenv:latest

### ISSUE THREAD

**Issue by afrancoc2000** [Azure/Hyperledger-Fabric-on-Azure-Kubernetes-Service#11]
The hyperledger team decided to delete the latest tag from the hyperledger/fabric-ccenv image and now my chaincode doesn't work because of it, can you update the image to use hyperledger/fabric-ccenv:1.4?

Thanks

**Comment by chintanr97** [comment]
@afrancoc2000 acknowledging it. We have started working on modifying the peer deployment files already.

**Comment by btl5037** [comment]
@chintanr97 We released Fabric 1.4.8 that provides a fix for this by setting the default builder to `1.4` instead of latest. Though it is still recommended that you would be setting these properties yourself.

**Comment by chintanr97** [comment]
Thanks Brett for the information. Yes, we are making the required changes to overwrite the `core.yaml` file default values for these images.

**Comment by chintanr97** [comment]
Hi @afrancoc2000, sorry for delayed response. You can follow these steps to easily patch your required peer deployments. Please let us know if you face any issues in executing the steps and if it works for you. 

1. Please download the peer deployment script using the command:
`curl https://raw.githubusercontent.com/Azure/Hyperledger-Fabric-on-Azure-Kubernetes-Service/master/scripts/patchPeerDeployment.sh -o patchPeerDeployment.sh; chmod 777 patchPeerDeployment.sh`

2. Set the following peer deployment related variables before executing the script:
```
PEER_ORG_RESOURCE_GROUP="<peerOrgResourceGroupName>"
PEER_AKS_NAME="<peerOrgAKSClusterName>"
PEER_ORG_SUBSCRIPTION="<peerOrgSubscriptionId>"
```
3. Execute the script with following command:
`source patchPeerDeployment.sh $PEER_ORG_SUBSCRIPTION $PEER_ORG_RESOURCE_GROUP $PEER_AKS_NAME`

4. Please wait for all your peer nodes to get patched. You can always check the status of your peer nodes, in different instance of the shell using the command:
`kubectl get pods -n hlf`

Please also note that the peer deployments will be modified directly in the next release and you would not have to patch them after that. I will update this thread, as soon as we make the next release for our AKS HLF template solution.

**Comment by afrancoc2000** [comment]
Hi @chintanr97 thank you for the response, I already had updated my peers using the deployment for couchDB peers in the "Hyperledger Fabric for Kubernetes" template, but thank you for the workaround.

I'll be waiting for the update thank you very much

**Comment by chintanr97** [comment]
Hi @afrancoc2000, the new release is published and marketplace solution has been upgraded too. Please find the Release notes for the new release [here](https://github.com/Azure/Hyperledger-Fabric-on-Azure-Kubernetes-Service/releases/tag/v3.0.0). Closing the issue for now, but please feel free to re-open.

**Comment by vinusheri** [comment]
Hi, I have an issue while issuing the composer network start command.
It shows: 
Error: Error trying to start business network. Error: No valid responses from any peers.
Response from attempted peer comms was an error: Error: failed to execute transaction 5adc5b9c7ea0f0157362a4aab85d99d92621d1acea83ffe37ee5e26b6976755b: error starting container: error starting container: Failed to generate platform-specific docker build: Failed to pull hyperledger/fabric-ccenv:latest: API error (404): manifest for hyperledger/fabric-ccenv:latest not found: manifest unknown: manifest unknown

Please help.
Thanks

**Comment by afrancoc2000** [comment]
@vinusheri you can try the fix in this post or you can also set this variables in your deployment

        - name: CORE_CHAINCODE_BUILDER
          value: hlfakstemplateoss.azurecr.io/hyperledger/abs-fabric-ccenv:1.4.8
        - name: CORE_CHAINCODE_GOLANG_RUNTIME
          value: hlfakstemplateoss.azurecr.io/hyperledger/abs-fabric-golangruntime:1.4.8
        - name: CORE_CHAINCODE_NODE_RUNTIME
          value: hlfakstemplateoss.azurecr.io/hyperledger/abs-fabric-nodejsruntime:1.4.8

Also the latest version of the template should work too.

Hope it helps

**Comment by vinusheri** [comment]
Thank you very much @afrancoc2000. I will try.
