### ISSUE TITLE
AKS kubernetes versions not compatible

### ISSUE THREAD

**Issue by afrancoc2000** [Azure/Hyperledger-Fabric-on-Azure-Kubernetes-Service#14]
Some of the options given by the template to choose for the kubernetes versions are not available any more in Azure AKS and generate errors when executing like the 1.16.7, which is not supported and is a deprecated version.

AKS versions should be updated.

Thanks

**Comment by KoDnessy** [comment]
Hi,

If you choose "default", it works but yes for other versions it doesn't work (I did not try 1.14).

Regards,

**Comment by DevOpsGeek1** [comment]
I have a query regarding version upgrade I have a Hyperledger-Fabric-on-Azure-Kubernetes-Service deployed with ARM template and I would like tp upgrade my AKS cluster from 1.16.10 to 1.17.11 , would Hyperledger-Fabric-on-Azure-Kubernetes-Service crash or down during the upgrade process?

**Comment by chintanr97** [comment]
We have corrected the Kubernetes Version and pinning in latest marketplace release. 

Currently the supported versions for HLF on AKS include `v1.18.x` (or less). Please note that `v1.19.x` (or later) is currently not supported for running HLF nodes.
