### ISSUE TITLE
Error while deploying HLF on Azure

### ISSUE THREAD

**Issue by rohitbuddharajuTanla** [Azure/Hyperledger-Fabric-on-Azure-Kubernetes-Service#33]
We tried deploying HLF as per the mentioned process on: https://github.com/Azure/Hyperledger-Fabric-on-Azure-Kubernetes-Service

Used a Azure custom template based deployment by pointing to private storage account. Template Validation passed & then Encountered the following error during the deployment stage 

Error:
{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"NotFound","message":"System.IO.FileNotFoundException: Function (HttpTrigger) does not exist\r\n at Kudu.Core.Functions.FunctionManager.GetFuncPathAndCheckExistence(String name) in C:\\Kudu Files\\Private\\src\\master\\Kudu.Core\\Functions\\FunctionManager.cs:line 395\r\n at Kudu.Core.Functions.FunctionManager.<GetFunctionSecretsAsync>d__12.MoveNext() in C:\\Kudu Files\\Private\\src\\master\\Kudu.Core\\Functions\\FunctionManager.cs:line 0\r\n--- End of stack trace from previous location where exception was thrown ---\r\n at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n at Kudu.Services.Functions.FunctionController.<GetSecrets>d__12.MoveNext() in C:\\Kudu Files\\Private\\src\\master\\Kudu.Services\\Functions\\FunctionController.cs:line 141\r\n--- End of stack trace from previous location where exception was thrown ---\r\n at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n at System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__3`1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()"}]}

**Comment by rohitbuddharajuTanla** [comment]
Additional Info on the error we are encountering:

Status: GatewayTimeout
Type: Microsoft.Web/sites/functions
Resource: test5280c/HttpTrigger

Status Message:
{
    "status": "Failed",
    "error": {
        "code": "GatewayTimeout",
        "message": "The gateway did not receive a response from 'Microsoft.Web' within the specified time period."
    }
}

**Comment by chintanr97** [comment]
Hi @rohitbuddharajuTanla,

We use linked templates as a part of “mainTemplate.json”. For this purpose, to deploy the template solution, the last 2 inputs (i.e. “_artifacts Location” and “_artifacts Location Sas Token”) need to be provided as follows:

1. Generate SAS token to list and read items in the storage account, that holds all the artifacts:
```
$ STORAGE_SUBSCRIPTION=<storageAccountSubscription>
$ STORAGE_RESOURCE_GROUP=<storageAccountResourceGroup>
$ STORAGE_ACCOUNT=<storageAccountName>

$ STORAGE_KEY=$(az storage account keys list --resource-group $STORAGE_RESOURCE_GROUP  --account-name $STORAGE_ACCOUNT --query "[0].value" | tr -d '"')
$ az storage account generate-sas --account-key $STORAGE_KEY --account-name $STORAGE_ACCOUNT --expiry `date -u -d "1 day" '+%Y-%m-%dT%H:%MZ'` --https-only --permissions lr --resource-types co --services b | tr -d '"'
```

The last command will output a SAS token which will be the input to the variable “_artifacts Location Sas Token”. Please note that the SAS token must be prefixed with a “?” before adding into template as the input (if not already present) – or the deployment will fail with the error received previously.

2. The storage account URI needs to be provided in the variable “_artifacts Location” so that the link to the dependent templates is maintained. For this purpose, please follow the syntax as given below:
`https://<storageAccountName>.blob.core.windows.net/<blobContainerName>/<pathToDirectoryHoldingTemplateAndArtifacts>/`

     The path to directory is up till the location where the “mainTemplate.json”, “hlf-marketplace.zip”, “artifacts”, and “nestedtemplates” are present. Please note that the trailing “/” is must – or the deployment will fail with the error received previously. 

Please also validate if all the required artifacts have been pushed to the storage account and are accessible using the above URIs produced. The fabric-tools should also be placed in public docker registry so that it can be pulled by the admin pod in the cluster to setup the pods. 

Please let me know if above recommendations were helpful.

Regards,
Chintan Rajvir

**Comment by rohitbuddharajuTanla** [comment]
Thanks for the quick response Chintan. Greatly appreciate your inputs.
Solved our problem. Cheers!

Thanks & Regards,
Rohit
